name: Deploy to AWS EC2

on:
  push:
    branches:
      - develop
      
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew bootJar
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.SECRET_KEY }}
        aws-region: ap-northeast-2

    - name: Copy files to the AWS S3 bucket
      run: |
        zip -j app.zip build/libs/*.jar appspec.yml scripts/*
        aws s3 cp app.zip s3://devyyj-github/app.zip

    - name: Deploy to AWS EC2
      run: |
        aws deploy create-deployment \
          --application-name pig_diary \
          --deployment-config-name CodeDeployDefault.OneAtATime \
          --deployment-group-name pig_diary_dev \
          --s3-location bucket=devyyj-github,bundleType=zip,key=app.zip
